### ISSUE TITLE
Big latency spikes in KioskController#show

### ISSUE THREAD

**Issue by decimalator** [osulp/kiosks#299]
The traces show upticks of > 4s in the rails.render_template span that appears to be getting called from KioskController#show.

Example traces:

https://app.datadoghq.com/apm/trace/663239909197689799?routing_hint=NaN
https://app.datadoghq.com/apm/trace/4315115369847077712?routing_hint=1552409508962&spanID=2281842623098576543

In case these go away before you can see them:

![Screen Shot 2019-03-12 at 1 28 29 PM](https://user-images.githubusercontent.com/1882223/54233832-05ed5300-44cb-11e9-9688-9759bc018988.png)

**Comment by revgum** [comment]
Data structure returned by `#show` includes `collection => slides` now and that expands the size of the resultant json to the donor kiosk by a magnitude. We have a few options that come to mind;

- refactor https://github.com/osulp/kiosks/blob/master/app/views/kiosk/show.json.jbuilder so that the data structure has `{ slides:, collection: }` and the application updated to account for this change (seems like a lot of refactoring)
- add Rails caching to this view and set the refresh time to something like 24 hours (and clear the cache when a slide is added/removed/updated) so that the render time for this json is only slow once a day
